# Generated by Django 4.0.1 on 2022-02-07 18:32

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Kurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('shortdesc', models.TextField(blank=True, max_length=200, verbose_name='Краткое описание')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='Изображение')),
                ('catid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='catid', to='infopages.kcat', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='№')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст')),
                ('kurseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurseid', to='infopages.kurse', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurseid', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=5, verbose_name='Номер модуля')),
                ('result_int', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=3, verbose_name='Баллы')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст вопроса')),
                ('kursid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurs', to='infopages.kurse', verbose_name='Модуль')),
                ('stepid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stepid', to='infopages.step', verbose_name='Урок')),
            ],
            options={
                'verbose_name': ' Вопрос',
                'verbose_name_plural': ' Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Nazn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurse', models.ManyToManyField(related_name='kurse', to='infopages.Kurse', verbose_name='Доступные модули')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Назначение',
                'verbose_name_plural': 'Назначения',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100, verbose_name='Ответ')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Верный ответ')),
                ('questionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionid', to='infopages.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': ' Ответ',
                'verbose_name_plural': ' Ответы',
            },
        ),
    ]
